include_recipe "pivotal_workstation::homebrew"
include_recipe "1kb_workstation::php53"
include_recipe "pivotal_workstation::mysql"
include_recipe "pivotal_workstation::mongodb"
include_recipe "pivotal_workstation::postgres"